const projects = [
  {title:'Cozinha planejada', category:'Cozinhas', image:'/images/projeto-cozinha-1.jpg'},
  {title:'Quarto planejado', category:'Quartos', image:'/images/projeto-quarto-1.jpg'},
  {title:'Armários planejados', category:'Dormitórios', image:'/images/projeto-sala-1.jpg'},
  {title:'Cozinha e área de serviço', category:'Cozinhas', image:'/images/projeto-instagram-1.jpg'},
];
export default function Home(){return <main>
<header className="nav"><a className="brand" href="#inicio"><b>MADE</b><span>MADEIRA DESIGN</span></a><nav><a href="#projetos">Projetos</a><a href="#solucoes">Soluções</a><a href="#sobre">Sobre</a><a href="#processo">Como funciona</a><a href="#contato">Contato</a></nav><a className="navcta" href="#contato">Orçamento ↗</a></header>
<section id="inicio" className="hero"><div className="hero-copy"><small>MÓVEIS PLANEJADOS</small><h1>Móveis sob medida.<br/><em>Do seu jeito.</em></h1><p>Projetos personalizados que unem funcionalidade, estética e atenção a cada detalhe.</p><a className="button" href="#projetos">Conheça nossos projetos <span>→</span></a></div><div className="hero-image"><img src="/images/projeto-cozinha-2.jpg" alt="Projeto de cozinha planejada da MADE"/></div></section>
<section id="projetos" className="projects"><div className="section-head"><div><small>NOSSOS PROJETOS</small><h2>Ambientes pensados<br/>para você.</h2></div><p>Projetos reais, feitos sob medida para diferentes espaços, necessidades e estilos.</p></div><div className="grid">{projects.map((p,i)=><article className={i===0?'featured':''} key={p.title}><img src={p.image} alt={p.title}/><div><small>{p.category}</small><h3>{p.title}</h3></div></article>)}</div></section>
<section id="solucoes" className="statement"><small>MADEIRA DESIGN</small><h2>Mais que móveis,<br/><em>criamos espaços.</em></h2><div className="features"><div><b>01</b><h3>Projetos personalizados</h3><p>Cada projeto nasce das medidas, necessidades e estilo de cada ambiente.</p></div><div><b>02</b><h3>Funcionalidade</h3><p>Soluções pensadas para aproveitar melhor cada espaço.</p></div><div><b>03</b><h3>Acabamentos</h3><p>Composições que acompanham o gosto e a personalidade de cada cliente.</p></div><div><b>04</b><h3>Acompanhamento</h3><p>Do primeiro contato à instalação, com atenção em cada etapa.</p></div></div></section>
<section id="sobre" className="about"><div className="about-image"><img src="/images/projeto-sala-2.jpg" alt="Armário planejado da MADE"/></div><div className="about-copy"><small>SOBRE A MADE</small><h2>Seu espaço merece<br/><em>um projeto pensado para ele.</em></h2><p>A MADE Madeira Design trabalha com móveis planejados e sob medida, transformando ideias em ambientes funcionais, bonitos e personalizados.</p><p>Mais do que preencher espaços, nosso trabalho é criar soluções que façam sentido para quem vai viver neles.</p><a href="#contato">Conheça a MADE →</a></div></section>
<section id="processo" className="process"><small>COMO FUNCIONA</small><h2>Do projeto à realização.</h2><div className="steps"><div><b>01</b><h3>Conversamos</h3><p>Entendemos suas ideias, necessidades e expectativas.</p></div><div><b>02</b><h3>Projetamos</h3><p>Criamos uma solução pensada para o seu espaço.</p></div><div><b>03</b><h3>Produzimos</h3><p>Damos vida ao projeto com cuidado e precisão.</p></div><div><b>04</b><h3>Instalamos</h3><p>Finalizamos tudo para você aproveitar seu novo ambiente.</p></div></div></section>
<section id="contato" className="contact"><div><small>VAMOS CONVERSAR?</small><h2>Vamos transformar<br/><em>seu ambiente?</em></h2><p>Conte um pouco sobre o que você imagina. A gente cuida do resto.</p></div><a className="button light" href="https://wa.me/558198722042" target="_blank" rel="noreferrer">Solicitar orçamento via WhatsApp →</a></section>
<footer><div className="brand"><b>MADE</b><span>MADEIRA DESIGN</span></div><p>© 2026 MADE Madeira Design. Todos os direitos reservados.</p></footer>
</main>}
