const projects = [
  {title:'Cozinha planejada', category:'Cozinhas', image:'/images/projeto-cozinha-instalacao.jpg'},
  {title:'Quarto planejado', category:'Quartos', image:'/images/projeto-quarto-1.jpg'},
  {title:'Armários planejados', category:'Dormitórios', image:'/images/projeto-sala-1.jpg'},
  {title:'Cozinha e área de serviço', category:'Cozinhas', image:'/images/projeto-instagram-1.jpg'},
];
export default function Home(){return <main>
<header className="nav"><a className="brand" href="#inicio"><b>MADE</b><span>MADEIRA DESIGN</span></a><nav><a href="#projetos">Projetos</a><a href="#solucoes">Soluções</a><a href="#sobre">Sobre</a><a href="#processo">Como funciona</a><a href="#contato">Contato</a></nav><a className="navcta" href="#contato">Orçamento ↗</a></header>
<section id="inicio" className="hero"><div className="hero-copy"><small>MÓVEIS PLANEJADOS</small><h1>Móveis sob medida.<br/><em>Do seu jeito.</em></h1><p>Projetos personalizados que unem funcionalidade, estética e atenção a cada detalhe.</p><a className="button" href="#projetos">Conheça nossos projetos <span>→</span></a></div><div className="hero-image"><img src="/images/projeto-cozinha-hero.jpg" alt="Projeto de cozinha planejada da MADE"/></div></section>
<section id="projetos" className="projects"><div className="section-head"><div><small>NOSSOS PROJETOS</small><h2>Ambientes pensados<br/>para você.</h2></div><p>Projetos reais, feitos sob medida para diferentes espaços, necessidades e estilos.</p></div><div className="grid">{projects.map((p,i)=><article className={i===0?'featured':''} key={p.title}><img src={p.image} alt={p.title}/><div><small>{p.category}</small><h3>{p.title}</h3></div></article>)}</div></section>
<section id="solucoes" className="statement"><small>MADEIRA DESIGN</small><h2>Mais que móveis,<br/><em>criamos espaços.</em></h2><div className="features"><div><b>01</b><h3>Projetos personalizados</h3><p>Cada projeto nasce das medidas, necessidades e estilo de cada ambiente.</p></div><div><b>02</b><h3>Funcionalidade</h3><p>Soluções pensadas para aproveitar melhor cada espaço.</p></div><div><b>03</b><h3>Acabamentos</h3><p>Composições que acompanham o gosto e a personalidade de cada cliente.</p></div><div><b>04</b><h3>Acompanhamento</h3><p>Do primeiro contato à instalação, com
